// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTecUor9Ex_ext_K2_8q-K5pnsFliuExY',
    appId: '1:841781635918:web:e1c9ba8fa9d55b053e8c1f',
    messagingSenderId: '841781635918',
    projectId: 'go-study-83a44',
    authDomain: 'go-study-83a44.firebaseapp.com',
    storageBucket: 'go-study-83a44.firebasestorage.app',
    measurementId: 'G-4GY6885ZNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_Q1kR_TlR_CZRPzJ5u4cDl7pnEynHLM',
    appId: '1:841781635918:android:724e45d175af6eb33e8c1f',
    messagingSenderId: '841781635918',
    projectId: 'go-study-83a44',
    storageBucket: 'go-study-83a44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDddq1fX211eKK9zTFWBTCrzpzjLxr1vpQ',
    appId: '1:841781635918:ios:420921751c0968313e8c1f',
    messagingSenderId: '841781635918',
    projectId: 'go-study-83a44',
    storageBucket: 'go-study-83a44.firebasestorage.app',
    androidClientId: '841781635918-hrgv50mfenm1leemnombremt890rpj5l.apps.googleusercontent.com',
    iosClientId: '841781635918-2iltl8atlmkrl3bu266qn8ns8443haq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.goStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDddq1fX211eKK9zTFWBTCrzpzjLxr1vpQ',
    appId: '1:841781635918:ios:420921751c0968313e8c1f',
    messagingSenderId: '841781635918',
    projectId: 'go-study-83a44',
    storageBucket: 'go-study-83a44.firebasestorage.app',
    androidClientId: '841781635918-hrgv50mfenm1leemnombremt890rpj5l.apps.googleusercontent.com',
    iosClientId: '841781635918-2iltl8atlmkrl3bu266qn8ns8443haq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.goStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTecUor9Ex_ext_K2_8q-K5pnsFliuExY',
    appId: '1:841781635918:web:dfc8cd5d2398c9a53e8c1f',
    messagingSenderId: '841781635918',
    projectId: 'go-study-83a44',
    authDomain: 'go-study-83a44.firebaseapp.com',
    storageBucket: 'go-study-83a44.firebasestorage.app',
    measurementId: 'G-Y1HH074G6N',
  );

}